### ISSUE TITLE
How to activte the code?

### ISSUE THREAD

**Issue by jasmeetsingr** [dougbot01/IMU_Steering_Bot#1]
Thank you for writing this code. somehow I managed to get a MINIMU-9 v2, you said:

"By default, motion is disabled to prevent the robot from turning when you first connect it to power."
I wonder if you can tell how to enable motion, I looked into the code but I couldn't find a way to do it.

Regards,
FarHorizon

**Comment by dougbot01** [comment]
The commands are part of Steering.ino. You can enable by sending a 1,
disable by sending 0.

Regards
dougbot

**Comment by jasmeetsingr** [comment]
Thank you for responding, one reason I couldn't notice it that I couldn't understand (being newbie) that default serial monitor setting will not show messages, it was giving me wired chararcters, till I changed boud rate and Carriage return in serial monitor. However my inputs does not meet any reaction.

It could be that Messenger libraries are not compatible with new Arduino release. Do you have the chance to test your program with the recent Arduino and Messenger versions or maybe with the new CMDMessenger? I had to modify some files to escape many compiling errors.

Regards,
FarHorizon

**Comment by dougbot01** [comment]
Hi,

Unfortunately, I no longer have the hardware so cannot test any software
updates. This is just example code I shared in case it helps anyone, not a
maintained release. I'm ok answering questions as time permits, but will
not be making any changes to the code.

Regards
dougbot
